/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RentServiceLocationRouteImport } from './routes/rent-$service-$location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentServiceLocationRoute = RentServiceLocationRouteImport.update({
  id: '/rent-$service-$location',
  path: '/rent-$service-$location',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rent-$service-$location': typeof RentServiceLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rent-$service-$location': typeof RentServiceLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rent-$service-$location': typeof RentServiceLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rent-$service-$location'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rent-$service-$location'
  id: '__root__' | '/' | '/rent-$service-$location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RentServiceLocationRoute: typeof RentServiceLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-$service-$location': {
      id: '/rent-$service-$location'
      path: '/rent-$service-$location'
      fullPath: '/rent-$service-$location'
      preLoaderRoute: typeof RentServiceLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RentServiceLocationRoute: RentServiceLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
